# Generated by Django 4.1.7 on 2023-03-03 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_name', models.TextField(max_length=50, verbose_name='Объект учёта')),
                ('object_people', models.TextField(max_length=50, verbose_name='Ответственное лицо')),
                ('object_cabinet', models.IntegerField(verbose_name='Номер кабинета')),
            ],
        ),
    ]
